/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#e5e2e1",
        "on-error": "#690005",
        "on-primary-fixed": "#1c1b1b",
        "secondary-container": "#604403",
        "secondary-fixed-dim": "#e9c176",
        "surface-container-high": "#282a2b",
        "inverse-surface": "#e2e2e2",
        "tertiary-container": "#0e0900",
        "background": "#050505",
        "obsidian-deep": "#050505",
        "surface-variant": "#1a1c1c",
        "secondary-fixed": "#ffdea5",
        "on-secondary-container": "#dab36a",
        "surface-container": "#0c0f0f",
        "on-tertiary-fixed-variant": "#574500",
        "on-secondary": "#412d00",
        "on-primary-container": "#7b7979",
        "surface-tint": "#c9c6c5",
        "on-tertiary": "#3c2f00",
        "primary-fixed-dim": "#c9c6c5",
        "error": "#ffb4ab",
        "surface-container-low": "#121414",
        "tertiary": "#e9c349",
        "primary-container": "#0a0a0a",
        "on-surface": "#e2e2e2",
        "error-container": "#93000a",
        "outline": "#8e9192",
        "outline-variant": "#444748",
        "tertiary-fixed-dim": "#e9c349",
        "surface-dim": "#0c0f0f",
        "on-tertiary-fixed": "#241a00",
        "on-surface-variant": "#c4c7c7",
        "inverse-primary": "#5f5e5e",
        "inverse-on-surface": "#2f3131",
        "sepia-shadow": "#594632",
        "glass-surface": "rgba(255, 255, 255, 0.03)",
        "on-secondary-fixed": "#261900",
        "gold-shimmer": "#e2c881",
        "surface-bright": "#38393a",
        "on-tertiary-container": "#947600",
        "on-background": "#e2e2e2",
        "on-error-container": "#ffdad6",
        "surface": "#050505",
        "secondary": "#e9c176",
        "surface-container-highest": "#333535",
        "tertiary-fixed": "#ffe088",
        "on-secondary-fixed-variant": "#5d4201",
        "primary": "#c9c6c5",
        "on-primary": "#313030",
        "surface-container-lowest": "#020202",
        "on-primary-fixed-variant": "#474646"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1440px",
        "gutter": "32px",
        "section-padding": "160px",
        "inner-padding": "60px",
        "element-gap": "24px"
      },
      fontFamily: {
        "headline-md": ["Playfair Display"],
        "body-lg": ["Montserrat"],
        "display-lg-mobile": ["Playfair Display"],
        "headline-lg": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
        "body-md": ["Montserrat"],
        "label-caps": ["Sora"]
      },
      fontSize: {
        "headline-md": ["36px", {"lineHeight": "1.3", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "1.7", "letterSpacing": "0.02em", "fontWeight": "300"}],
        "display-lg-mobile": ["56px", {"lineHeight": "1.1", "fontWeight": "800"}],
        "headline-lg": ["48px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "display-lg": ["96px", {"lineHeight": "1.0", "letterSpacing": "-0.04em", "fontWeight": "800"}],
        "body-md": ["16px", {"lineHeight": "1.8", "fontWeight": "300"}],
        "label-caps": ["11px", {"lineHeight": "1.0", "letterSpacing": "0.3em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
